media:
  input: media
  output: pagescms-sample/media
content:
  - name: homepage
    label: Homepage
    type: file
    path: index.md
    fields:
      - name: title
        label: Page Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Content
        type: rich-text
  - name: docs
    label: Documentation
    type: collection
    path: 'docs'
    view:
      fields: [ title, nav_order, description ]
    fields:
      - name: title
        label: Title
        type: string
      - name: nav_order
        label: Navigation Order
        type: number
        description: Order in navigation menu
      - name: description
        label: Description
        type: string
        description: Page description for SEO
      - name: body
        label: Content
        type: rich-text
  - name: config
    label: Site Configuration
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Site Title
        type: string
      - name: description
        label: Site Description
        type: string
      - name: url
        label: Site URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: baseurl
        label: Base URL
        type: string
        description: Subpath of your site (e.g. /blog)
      - name: footer_content
        label: Footer Content
        type: string
