title: ドキュメントサイト
description: Just the Docsで構築された包括的なドキュメントサイト
url: https://himaratsu.github.io
baseurl: /pagescms-sample

# Theme
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: nil

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchor links
heading_anchors: true

# Aux links
aux_links:
  "GitHubリポジトリ":
    - "https://github.com/himaratsu/pagescms-sample"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Sorting order for navigation links
nav_sort: case_insensitive

# Footer content
footer_content: "JekyllとJust the Docsテーマで構築"

# Footer last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Google Analytics (optional)
# ga_tracking: UA-NNNNNNNN-N
# ga_tracking_anonymize_ip: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
